[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/members/*"
  to = "/members/:splat"
  status = 200
  conditions = { Role = ["member", "admin"] }

[[redirects]]
  from = "/members/*"
  to = "/login/"
  status = 302
